# LTXV LoRA Training Configuration

# Model configuration
model:
  model_source: "LTXV_2B_0.9.6_DEV" # Options: "LTXV_13B_097_DEV", "LTXV_2B_0.9.6_DEV", "LTXV_2B_0.9.5", "LTXV_2B_0.9.1", "LTXV_2B_0.9.0", or a HF repo/local path
  training_mode: "lora" # Options: "lora" or "full"
  load_checkpoint: null # Path to checkpoint file or directory to resume from. If directory, latest checkpoint will be used.

# LoRA configuration
lora:
  rank: 128
  alpha: 192
  dropout: 0.1
  target_modules:
      - to_k
      - to_q
      - to_v
      - to_out.0
      - net.0.proj
      - net.2

# Conditioning configuration
conditioning:
  mode: "none" # Options: "none", "reference_video"
  first_frame_conditioning_p: 1.0

# Optimization configuration
optimization:
  learning_rate: 1e-4
  steps: 148325
  batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer_type: "adamw8bit" # Options: "adamw" or "adamw8bit"
  scheduler_type: "linear" # Options: "constant", "linear", "cosine", "cosine_with_restarts", "polynomial"
  scheduler_params: {}
  enable_gradient_checkpointing: true

# Acceleration optimization
acceleration:
  mixed_precision_mode: "bf16" # Options: "no", "fp16", "bf16"
  quantization: null # Options: null, "int8-quanto", "int4-quanto", "int2-quanto", "fp8-quanto", "fp8uz-quanto"
  load_text_encoder_in_8bit: true # Load text encoder in 8-bit precision to save memory
  compile_with_inductor: false
  compilation_mode: "reduce-overhead" # Options: "default", "reduce-overhead", "max-autotune"

# Data configuration
data:
  dataset_manifest_path: datasets/real-clips-121/.precomputed/dataset-right.json
  preprocessed_data_root: datasets/real-clips-121/.precomputed
  num_dataloader_workers: 2

# Validation configuration
validation:
  prompts:
    - "POV, Move forward and turn right"
    - "POV, Move forward and turn right"
    # - "POV, Continue straight ahead down the hallway, passing by the tables on the right, stop at the red object of the left."
    # - "POV, Walk straight ahead, passing the chairs on your right, until you reach the white cabinet ahead. Stop at the cabinet."
    # - "POV, Walk straight ahead down the hall, passing the black couch on your left until you reach the end of the hall, then stop in front of the stairs."
    # - "POV, Walk straight ahead approaching the black couch, then turn left in front of the couch, and stop at the white table."
  images:
    - "datasets/validation_images/IMG_4393_432_553_TURN_LEFT_MOVE_FORWARD_firstframe.png"
    - "datasets/validation_images/LaunchPad_clips/IMG_4351_192_313_MOVE_FORWARD_TURN_RIGHT_firstframe.png"
    # - "datasets/vln_n1_filtered/validation_images/scene3.jpg"
    # - "datasets/vln_n1_filtered/validation_images/scene4.jpg"
    # - "datasets/vln_n1_filtered/validation_images/scene5.jpg"
    # - "datasets/vln_n1_filtered/validation_images/scene5.jpg"
  negative_prompt: "worst quality, inconsistent motion, blurry, jittery, distorted"
  video_dims: [480, 256, 121] # [width, height, frames]
  seed: 42
  inference_steps: 50
  interval: 148325 # Set to null to disable validation
  videos_per_prompt: 1
  guidance_scale: 3.8

# Checkpoint configuration
checkpoints:
  interval: 148325 # Save a checkpoint every N steps, set to null to disable
  keep_last_n: -1 # Keep only the N most recent checkpoints, set to -1 to keep all

# Flow matching configuration
flow_matching:
  timestep_sampling_mode: "shifted_logit_normal" # Options: "uniform", "shifted_logit_normal"
  timestep_sampling_params: {}

# HuggingFace Hub configuration
hub:
  push_to_hub: false # Whether to push the model weights to the Hugging Face Hub
  hub_model_id: null # Hugging Face Hub repository ID (e.g., 'username/repo-name'). Must be provided if `push_to_hub` is set to True

# W&B configuration
wandb:
  enabled: true  # Set to true to enable W&B logging
  project: "ltxv-trainer"
  entity: null  # Your W&B username or team
  tags: []
  log_validation_videos: true

# General configuration
seed: 42
output_dir: "outputs/0220-full-right"
